### ISSUE TITLE
initial install issue

### ISSUE THREAD

**Issue by solasdev** [Ghirensics/ghiro#13]
When trying to get the app to run from command line after installing required packages i run -

sudo python manage.py syncdb

But get...

Traceback (most recent call last):

  File "manage.py", line 10, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute

    settings.INSTALLED_APPS

  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__

    self._setup(name)

  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup

    self._wrapped = Settings(settings_module)

  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__

    mod = importlib.import_module(self.SETTINGS_MODULE)

  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module

    __import__(name)

  File "/home/ghiro-0.2.1/ghiro/__init__.py", line 8, in <module>

    from lib.db import mongo_connect

  File "/home/ghiro-0.2.1/lib/db.py", line 29, in <module>

    db = mongo_connect()

  File "/home/ghiro-0.2.1/lib/db.py", line 21, in mongo_connect

    db = Database(MongoClient(settings.MONGO_URI), settings.MONGO_DB)

  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__

    self._setup(name)

  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup

    self._wrapped = Settings(settings_module)

  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__

    mod = importlib.import_module(self.SETTINGS_MODULE)

  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module

    __import__(name)

  File "/home/ghiro-0.2.1/ghiro/settings.py", line 89, in <module>

    "django.core.context_processors.request",

TypeError: can only concatenate list (not "tuple") to list

**Comment by jekil** [comment]
You are right, there was version mismatch on pymongo in requirements.txt (you need pymongo release 2.8).
You can fix just re-downloading the package from ghiro website.

Thank you for reporting the issue.
