### ISSUE TITLE
MySQL server as gone away

### ISSUE THREAD

**Issue by jekil** [Ghirensics/ghiro#9]
The following error was reported:

2015-09-15 08:45:19,033 [DEBUG] lib.analyzer.processing - No tasks. Waiting...
2015-09-15 08:45:20,036 [DEBUG] lib.analyzer.processing - No tasks. Waiting...
2015-09-15 08:45:21,039 [DEBUG] lib.analyzer.processing - No tasks. Waiting...
2015-09-15 08:45:22,042 [DEBUG] lib.analyzer.processing - No tasks. Waiting...
2015-09-15 08:45:23,053 [DEBUG] lib.analyzer.processing - Processing task 4502
2015-09-15 08:45:23,067 [DEBUG] lib.analyzer.processing - No tasks. Waiting...
2015-09-15 08:45:23,140 [ERROR] lib.analyzer.processing - Critical error in plugin <class 'plugins.analyzer.gexiv.GexivAnalyzer'>, skipping: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/var/www/html/ghiro/lib/analyzer/processing.py", line 57, in _process_image
    output = current.run(task)
  File "/var/www/html/ghiro/plugins/analyzer/gexiv.py", line 120, in run
    self._get_exif()
  File "/var/www/html/ghiro/plugins/analyzer/gexiv.py", line 64, in _get_exif
    self._add_key(key, self.metadata.get(key))
  File "/var/www/html/ghiro/plugins/analyzer/gexiv.py", line 49, in _add_key
    add_metadata_description(key, self.metadata.get_tag_description(key))
  File "/var/www/html/ghiro/lib/utils.py", line 108, in add_metadata_description
    AnalysisMetadataDescription.objects.get(key=key.lower())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.exe:cute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')
2015-09-15 08:45:24,073 [DEBUG] lib.analyzer.processing - No tasks. Waiting...
2015-09-15 08:45:25,080 [DEBUG] lib.analyzer.processing - Processing task 4503
2015-09-15 08:45:25,093 [DEBUG] lib.analyzer.processing - Queue full. Waiting...
2015-09-15 08:45:26,102 [DEBUG] lib.analyzer.processing - Queue full. Waiting...
2015-09-15 08:45:27,107 [DEBUG] lib.analyzer.processing - Queue full. Waiting...
2015-09-15 08:45:27,927 [ERROR] lib.analyzer.processing - Critical error in plugin <class 'plugins.analyzer.hashcomparer.HashComparerAnalyzer'>, skipping: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/var/www/html/ghiro/lib/analyzer/processing.py", line 57, in _process_image
    output = current.run(task)
  File "/var/www/html/ghiro/plugins/analyzer/hashcomparer.py", line 27, in run
    hash_lists = List.objects.filter(cipher=key).filter(Q(owner=task.owner) | Q(public=True))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 320, in __get__
    rel_obj = qs.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')
2015-09-15 08:45:28,035 [INFO] lib.analyzer.processing - Processed task 4502 with success
Process AnalysisRunner-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/var/www/html/ghiro/lib/analyzer/processing.py", line 39, in run
    self._process_image(task)
  File "/var/www/html/ghiro/lib/analyzer/processing.py", line 77, in _process_image
    task.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 570, in save_base
    with transaction.commit_on_success_unless_managed(using=using, savepoint=False):
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 280, in __enter__
    connection.set_autocommit(False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 243, in autocommit
    _mysql.connection.autocommit(self, on)
OperationalError: (2006, 'MySQL server has gone away')
2015-09-15 08:45:28,110 [DEBUG] lib.analyzer.processing - Queue full. Waiting...
2015-09-15 08:45:29,113 [DEBUG] lib.analyzer.processing - Queue full. Waiting...
2015-09-15 08:45:30,115 [DEBUG] lib.analyzer.processing - Queue full. Waiting...
2015-09-15 08:45:31,117 [DEBUG] lib.analyzer.processing - Queue full. Waiting...
2015-09-15 08:45:32,120 [DEBUG] lib.analyzer.processing - Queue full. Waiting..

**Comment by jekil** [comment]
It depends by mysql connection timeout settings. This can be configured using CONN_MAX_AGE in the database connection options.

**Comment by jekil** [comment]
Fixed in f0b6284361c2a91c69acb880d0faa917560bee03

**Comment by bobstay** [comment]
thank you for your help i test whith this
in /var/www/html/ghiro/ghiro/loacal_settings.py
LOCAL_SETTINGS = True
from .settings import *

DATABASES = {
    'default': {
        # Engine type. Ends with 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'ENGINE': 'django.db.backends.sqlite3',
        # Database name or path to database file if using sqlite3.
        'NAME': 'db.sqlite',
        # Credntials. The following settings are not used with sqlite3.
        'USER': '',
        'PASSWORD': '',
        # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'HOST': '',
        # Set to empty string for default port.
        'PORT': '',
        # Set timeout (avoids SQLite "database is locked" errors).
        'timeout': 300,
        # The lifetime of a database  persistent connection, in seconds.
        "CONN_MAX_AGE": 0,
    }
}

do not forget: python manage.py syncdb

**Comment by bobstay** [comment]
Today db connection is dead test with  "CONN_MAX_AGE": 60,

**Comment by jekil** [comment]
what do you mean with "is dead", do you have any log?

**Comment by bobstay** [comment]
its the same log "MySQL server has gone away", mysql deconnection is one thing but a reconnection is expected?

**Comment by jekil** [comment]
Sure, it is.

**Comment by jekil** [comment]
We tested the "CONN_MAX_AGE": 60 with mysql for a couple of hours and had no issue, please describe better yours.

**Comment by bobstay** [comment]
ghiro works for now, we'll see tomorrow, it is my home :) 6:00 p.m.

**Comment by bobstay** [comment]
I investigated,

in upstart/mysql:

^G150921  9:52:29 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150921  9:52:29 [Note] /usr/sbin/mysqld (mysqld 5.5.44-0ubuntu0.14.04.1) starting as process 931 ...
/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
^G/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
^G/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
mysqld is alive
Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.
^G150922  8:39:02 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead./usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!

150922  8:39:02 [Note] /usr/sbin/mysqld (mysqld 5.5.44-0ubuntu0.14.04.1) starting as process 963 ...
^G/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
mysqld is alive
Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.

in mongodb:

Tue Sep 22 08:44:19.395 [initandlisten] connection accepted from 127.0.0.1:48015 #20 (20 connections now open)
Tue Sep 22 08:44:19.418 [initandlisten] connection accepted from 127.0.0.1:48016 #21 (21 connections now open)
Tue Sep 22 08:44:19.836 [initandlisten] connection accepted from 127.0.0.1:48017 #22 (22 connections now open)
Tue Sep 22 08:44:25.006 [initandlisten] connection accepted from 127.0.0.1:48018 #23 (23 connections now open)
Tue Sep 22 08:44:25.368 [conn19] command ghirodb.$cmd command: { count: "analyses", fields: null, query: { ela.ela_image: "e8a955d1c2ad4c56a706595e7e6af834c06836735525b6e993a8e03f7f5c15ce17435dbe" } } ntoreturn:1 keyUpdates:0 locks(micros) r:333388 reslen:48 333ms
Tue Sep 22 08:47:07.431 [initandlisten] connection accepted from 127.0.0.1:48019 #24 (24 connections now open)
Tue Sep 22 16:34:55.842 [conn5] insert ghirodb.fs.chunks ninserted:1 keyUpdates:0 locks(micros) w:28258 129ms
Tue Sep 22 16:34:56.400 [conn5] insert ghirodb.fs.chunks ninserted:1 keyUpdates:0 locks(micros) w:390001 390ms
Tue Sep 22 16:35:00.083 [conn1] insert ghirodb.fs.files ninserted:1 keyUpdates:0 locks(micros) w:153 419ms
Tue Sep 22 16:35:06.455 [conn12] insert ghirodb.fs.chunks ninserted:1 keyUpdates:0 locks(micros) w:228990 229ms
Tue Sep 22 16:35:11.305 [conn12] insert ghirodb.fs.chunks ninserted:1 keyUpdates:0 locks(micros) w:233414 233ms
Tue Sep 22 16:35:26.592 [conn3] command ghirodb.$cmd command: { count: "analyses", fields: null, query: { ela.ela_image: "2e44d5811bcb4b0b87ccfcd2ec15827c66a91062a4348299080bbb545f7441e0cc44aded" } } ntoreturn:1 keyUpdates:0 locks(micros) r:159205 reslen:48 159ms
Wed Sep 23 09:17:37.621 [conn17] insert ghirodb.fs.chunks ninserted:1 keyUpdates:0 locks(micros) w:258584 259ms
Wed Sep 23 09:17:38.312 [conn17] insert ghirodb.fs.files ninserted:1 keyUpdates:0 locks(micros) w:105413 105ms
Wed Sep 23 09:17:42.579 [conn13] insert ghirodb.fs.chunks ninserted:1 keyUpdates:0 locks(micros) w:325738 327ms
Wed Sep 23 09:17:43.177 [conn13] insert ghirodb.fs.chunks ninserted:1 keyUpdates:0 locks(micros) w:202401 202ms
Wed Sep 23 09:17:45.112 [conn12] insert ghirodb.fs.files keyUpdates:0 exception: E11000 duplicate key error index: ghirodb.fs.files.$sha1_unique  dup key: { : "b23d93a5248acf54f488b2ea94ae399d6d019318" } code:11000 locks(micros) w:113782 113ms
Wed Sep 23 09:17:45.438 [conn12] end connection 127.0.0.1:48007 (23 connections now open).

**Comment by jekil** [comment]
Mongodb logs are fine.
Mysql aren't, the error "Can't connect to local MySQL server" can be your issue. It is a mysql issue not a ghiro issue, please check your setup.

**Comment by bobstay** [comment]
ok thank you for your help, I'm still looking a bit and if I find it I will use appliance.
